//! Provider trait and provider-neutral request/response types.

use async_trait::async_trait;
use helm_core::{ContentBlock, Message, ProviderError};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Asynchronous language model provider capable of HELM chat/tool turns.
#[async_trait]
pub trait Provider: Send + Sync {
    /// Returns the stable provider name used in logs and diagnostics.
    fn name(&self) -> &'static str;

    /// Sends one chat turn to the provider and returns normalized content blocks.
    async fn chat(&self, request: ChatRequest) -> Result<ChatResponse, ProviderError>;
}

/// Provider-neutral chat request used by the ReAct agent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ChatRequest {
    /// Provider model identifier.
    pub model: String,
    /// Optional system prompt, mapped to provider-native system instructions.
    pub system: Option<String>,
    /// Conversation history in HELM's Anthropic-compatible message format.
    pub messages: Vec<Message>,
    /// Tool JSON schema definitions available to the model.
    pub tools: Vec<ToolSchema>,
    /// Maximum number of output tokens requested from the provider.
    pub max_tokens: u32,
    /// Sampling temperature requested from the provider.
    pub temperature: f32,
}

/// Provider-neutral chat response returned by every HELM provider.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ChatResponse {
    /// Provider response identifier.
    pub id: String,
    /// Ordered content blocks produced by the provider.
    pub content: Vec<ContentBlock>,
    /// Provider stop reason normalized for the ReAct loop.
    pub stop_reason: StopReason,
    /// Token usage reported by the provider.
    pub usage: Usage,
}

/// Normalized provider stop reasons.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model completed its answer without requesting more tool work.
    EndTurn,
    /// The model stopped because the output token limit was reached.
    MaxTokens,
    /// The model requested one or more tool invocations.
    ToolUse,
    /// The model stopped at a configured stop sequence.
    StopSequence,
}

/// Provider token usage for budget tracking and memory logs.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub struct Usage {
    /// Number of input tokens consumed by the request.
    pub input_tokens: u32,
    /// Number of output tokens generated by the response.
    pub output_tokens: u32,
}

/// JSON-schema declaration for one tool available to a provider.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolSchema {
    /// Tool name used by the model when requesting tool use.
    pub name: String,
    /// Human-readable tool behavior description.
    pub description: String,
    /// JSON Schema object describing the tool input.
    pub input_schema: Value,
}

#[cfg(test)]
mod tests {
    use helm_core::{ContentBlock, Message};
    use serde_json::json;

    use super::{ChatRequest, ChatResponse, StopReason, ToolSchema, Usage};

    #[test]
    fn stop_reason_serializes_to_provider_shape_happy_path() {
        let encoded = serde_json::to_value(StopReason::ToolUse).unwrap();
        assert_eq!(encoded, json!("tool_use"));
    }

    #[test]
    fn stop_reason_rejects_unknown_error_path() {
        let result = serde_json::from_value::<StopReason>(json!("done"));
        assert!(result.is_err());
    }

    #[test]
    fn chat_request_round_trips_edge_case_empty_tools() {
        let request = ChatRequest {
            model: "m".to_owned(),
            system: None,
            messages: vec![Message::user("hello")],
            tools: Vec::new(),
            max_tokens: 10,
            temperature: 0.0,
        };

        let encoded = serde_json::to_value(&request).unwrap();
        let decoded: ChatRequest = serde_json::from_value(encoded).unwrap();

        assert_eq!(decoded, request);
    }

    #[test]
    fn chat_response_round_trips_with_tool_schema() {
        let response = ChatResponse {
            id: "msg_1".to_owned(),
            content: vec![ContentBlock::Text("ok".to_owned())],
            stop_reason: StopReason::EndTurn,
            usage: Usage {
                input_tokens: 1,
                output_tokens: 2,
            },
        };
        let schema = ToolSchema {
            name: "shell".to_owned(),
            description: "run".to_owned(),
            input_schema: json!({"type": "object"}),
        };

        assert_eq!(schema.name, "shell");
        assert_eq!(
            serde_json::from_value::<ChatResponse>(serde_json::to_value(&response).unwrap())
                .unwrap(),
            response
        );
    }
}
